/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import Clases.Conexion;
import javax.swing.WindowConstants;


public class Editor extends javax.swing.JFrame {
    
    //Variables para JLabelNombreU
    String user, nombre_usuario;
    public static int sesion_usuario;

    public Editor() {
        initComponents();
        
        //Inicializando variables para el jlabel bienvenida
        user = Login.user;
        sesion_usuario = 1;
        
        setTitle("FamilyBoock  ||  Menu Principal  ||  Editor");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        Toolkit miPantalla = Toolkit.getDefaultToolkit();
        Image miIcono = miPantalla.getImage("src/imagenes/Icono.png");
        setIconImage(miIcono);
        
        ImageIcon wallPaper = new ImageIcon("src\\Imagenes\\WallPaperR.png");
        Icon icono = new ImageIcon(wallPaper.getImage().getScaledInstance(JL_Wallpaper.getWidth(), JL_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        JL_Wallpaper.setIcon(icono);
        this.repaint();
        
        
        //Codigo botones        
        
        ImageIcon JB_EU = new ImageIcon("src\\Imagenes\\EditAccount.png");
        Icon jb_eu = new ImageIcon(JB_EU.getImage().getScaledInstance(JB_EditarUsuario.getWidth(), JB_EditarUsuario.getHeight(), Image.SCALE_DEFAULT));
        JB_EditarUsuario.setIcon(jb_eu);
        this.repaint();
        
        ImageIcon JB_PF = new ImageIcon("src\\Imagenes\\EditProfile.png");
        Icon jb_pf = new ImageIcon(JB_PF.getImage().getScaledInstance(JB_Perfil.getWidth(), JB_Perfil.getHeight(), Image.SCALE_DEFAULT));
        JB_Perfil.setIcon(jb_pf);
        this.repaint();
        
        ImageIcon JB_T = new ImageIcon("src\\Imagenes\\Lista.png");
        Icon jb_t = new ImageIcon(JB_T.getImage().getScaledInstance(JB_Todos.getWidth(), JB_Todos.getHeight(), Image.SCALE_DEFAULT));
        JB_Todos.setIcon(jb_t);
        this.repaint();
        
        ImageIcon JB_A = new ImageIcon("src\\Imagenes\\AcercaDE.png");
        Icon jb_a = new ImageIcon(JB_A.getImage().getScaledInstance(JB_AcercaDe.getWidth(), JB_AcercaDe.getHeight(), Image.SCALE_DEFAULT));
        JB_AcercaDe.setIcon(jb_a);
        this.repaint();
        
        // fin codigo para botones
        
        // Codigo para cambiar el jlabel de bienbenida {
                
        try {
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select NombreU from usuario where NombreU = '" + user + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                
                nombre_usuario = rs.getString("NombreU");
                JL_NombreU.setText("Bienvenid@ " + nombre_usuario + " a FamilyBoock");
                
            }
            
        } catch (Exception e) {
            System.err.println("Se a producido un error:" + e);
        }
        
        // }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_Todos = new javax.swing.JToggleButton();
        JB_Perfil = new javax.swing.JToggleButton();
        JB_AcercaDe = new javax.swing.JToggleButton();
        JB_EditarUsuario = new javax.swing.JToggleButton();
        JL_Todos = new javax.swing.JLabel();
        JL_Perfil = new javax.swing.JLabel();
        JL_AcercaDe = new javax.swing.JLabel();
        JL_EditarUsuario = new javax.swing.JLabel();
        JL_NombreU = new javax.swing.JLabel();
        JL_Formato = new javax.swing.JLabel();
        JL_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(JB_Todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, 90));
        getContentPane().add(JB_Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 100, 90));

        JB_AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AcercaDeActionPerformed(evt);
            }
        });
        getContentPane().add(JB_AcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 100, 90));
        getContentPane().add(JB_EditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, 90));

        JL_Todos.setForeground(new java.awt.Color(204, 204, 204));
        JL_Todos.setText("Lista de usuarios");
        getContentPane().add(JL_Todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));

        JL_Perfil.setForeground(new java.awt.Color(204, 204, 204));
        JL_Perfil.setText("Editar perfil");
        getContentPane().add(JL_Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        JL_AcercaDe.setForeground(new java.awt.Color(204, 204, 204));
        JL_AcercaDe.setText("Acerca de");
        getContentPane().add(JL_AcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        JL_EditarUsuario.setForeground(new java.awt.Color(204, 204, 204));
        JL_EditarUsuario.setText("Gestionar usuarios");
        getContentPane().add(JL_EditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        JL_NombreU.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        JL_NombreU.setForeground(new java.awt.Color(255, 255, 255));
        JL_NombreU.setText("(Interfaz Prueba[No informacion])");
        getContentPane().add(JL_NombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JL_Formato.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        JL_Formato.setForeground(new java.awt.Color(255, 255, 255));
        JL_Formato.setText("FamilyBoock ®");
        getContentPane().add(JL_Formato, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));
        getContentPane().add(JL_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AcercaDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_AcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JB_AcercaDe;
    private javax.swing.JToggleButton JB_EditarUsuario;
    private javax.swing.JToggleButton JB_Perfil;
    private javax.swing.JToggleButton JB_Todos;
    private javax.swing.JLabel JL_AcercaDe;
    private javax.swing.JLabel JL_EditarUsuario;
    private javax.swing.JLabel JL_Formato;
    private javax.swing.JLabel JL_NombreU;
    private javax.swing.JLabel JL_Perfil;
    private javax.swing.JLabel JL_Todos;
    private javax.swing.JLabel JL_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
